### PR TITLE
Add comments — rules are there to be broken

### PR DESCRIPTION
**Pull request by matthew-andrews**
@ironsidevsquincy :wink:

### CODE REVIEW

**Comment by matthew-andrews** [comment]
I've put some PRs in to reduce the weight of these deps

**Comment by matthew-andrews** [comment]
http://git.svc.ft.com:8080/projects/STRAT_P/repos/o-comment-api/pull-requests/1/overview
http://git.svc.ft.com:8080/projects/STRAT_P/repos/o-comment-ui/pull-requests/1/overview
http://git.svc.ft.com:8080/projects/STRAT_P/repos/o-comment-utilities/pull-requests/1/overview
http://git.svc.ft.com:8080/projects/STRAT_P/repos/o-comments/pull-requests/3/overview

**Comment by ironsidevsquincy** [comment]
That's one way to do it. Hopefully should be temporary

**Comment by matthew-andrews** [comment]
maybe we can wait for those PRs to be merged to reduce the pain of this solution

**Comment by matthew-andrews** [comment]
Think this is good to go now @ironsidevsquincy ?

**Comment by ironsidevsquincy** [comment]
:dancers:  :+1: :dancers:

**Pull request merged**
