### PR TITLE
No more fancy, bandwidth-hogging backgrounds

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
And main image is now inlined

screen shot 2015-03-13 at 16 36 20

### CODE REVIEW

**Comment by matthew-andrews** [comment]
main image inlined on the LHS may have been veto'd by stakeholders — one to check with Dan S / George B — otherwise :+1:

**Comment by commuterjoy** [comment]
Personally I like the main image on the left

1. Often the FT's images are quite dull.  
2. It makes the design feel less like a medium et al rip off.

**Comment by commuterjoy** [comment]
3. Makes the text closer to the top off the page, which is more useful to the user.

**Comment by matthew-andrews** [comment]
let's see what they say next week

**Pull request merged**
