### PR TITLE
Last defence against crazy-big images

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i think we should just serve plain text when we fall back to capi v1

**Comment by matthew-andrews** [comment]
(instead of this)

**Comment by ironsidevsquincy** [comment]
means pulling out non-text from the body, which is a bigger piece of work

**Comment by matthew-andrews** [comment]
hmm… there's a quick way to do it

**Comment by matthew-andrews** [comment]
much prefer to be in control of the images we send down to clients…… #453

**Pull request closed without merging**
