### PR TITLE
npm re-install not needed

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
cc @commuterjoy @adgad

**Comment by commuterjoy** [comment]
This was here because `make smoke` used some of the pruned modules from the deploy step.

**Comment by matthew-andrews** [comment]
deploy shouldn't prune anymore :/

**Comment by matthew-andrews** [comment]
aha.  not yet merged this https://github.com/Financial-Times/next-build-tools/pull/10

**Pull request merged**
