### PR TITLE
Display people/orgs even if no v1-to-v2-mapping

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
As currently we're not using v2 data

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i'm using v2 data behind “mentionsV2” flag…

**Comment by ironsidevsquincy** [comment]
This is just for the people and organisations endpoints, that display the respective components - we're not displaying any v2 data in them, so using the v1-to-v2 mapping isn't absolutely necessary right now, but hopefully we'll start using it soon (e.g. linking to a stream page using the v2 uuid, etc)

**Comment by matthew-andrews** [comment]
ah ok. sweet.

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
